name: Java CI

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    
#     Build JAR:
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests
